version: '3.8'

services:
  # 1. RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    container_name: wms-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always

  # 2. Redis Cache
  redis:
    image: redis:alpine
    container_name: wms-redis
    ports:
      - "6379:6379"
    restart: always

  # 3. PostgreSQL database
  postgres:
    image: postgres:15-alpine
    container_name: wms-postgres
    environment:
      POSTGRES_USER: ${DB_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DB_POSTGRES_PASS}
      POSTGRES_DB: warehouse_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  # 4. MongoDB database
  mongodb:
    image: mongo:latest
    container_name: wms-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_MONGO_PASS}
    ports:
      - "27018:27017"
    volumes:
      - mongodata:/data/db
    restart: always

  # 5. SQL Server for IdentityService
  identity_sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: wms-identity-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${DB_IDENTITY_SQL_PASS}
    ports:
      - "1434:1433"
    volumes:
      - identity_sqldata:/var/opt/mssql
    restart: always

  # 6. SQL Server for OrderService
  order_sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: wms-order-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${DB_ORDER_SQL_PASS}
    ports:
      - "1435:1433"
    volumes:
      - order_sqldata:/var/opt/mssql
    restart: always

  # 7. Centralized logging UI
  seq:
    image: datalust/seq:latest
    container_name: wms-seq
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_NOAUTHENTICATION=true
    ports:
      - "8081:80"
      - "5341:5341"
    volumes:
      - seqdata:/data
    restart: always

volumes:
  pgdata:
  mongodata:
  identity_sqldata:
  order_sqldata:
  seqdata:
